### ISSUE TITLE
Save() does not save metadata

### ISSUE THREAD

**Issue by dynamix** [glycerine/offheap#1]
The Save() method just syncs the memory map with the disk, metadata like Population, ZeroUsed and so on is not stored. A Hashtable instantiated with a mmaped file is therefor corrupt (ZeroValue invalid, next Repopulate fails).

**Comment by glycerine** [comment]
Hi Martin @dynamix ,

Yes; serialization was never finished. I'm happy to review and merge your fix for this, but I don't have time to do it myself. Should you like to do it, please extend save_test.go with a test line like

	cv.So(h2.Population, cv.ShouldEqual, 2)

and then send me a pull-request with your implementation of serialization.  You can see that I started on adding capnproto serialization; but it is nowhere used and is thus incomplete, as you've pointed out.  I'm certainly not wedded to requiring capnproto for the serialization. It is simple and I know it well; the preliminary code is in the ohser/ subdirectory. I can offer guidance on how to use it if need be.

Also may I inquire: what do you require an offheap hashtable for?  Garbage collection got markedly better in go1.5.1, so the builtin map may now suffice, depending on your application.

Best regards,

Jason

**Comment by dynamix** [comment]
Hey Jason,

thanks for the quick reply. I just forked the repository and might send a PR soonish (depending on how much work it is going to be :grinning: ).

Regarding 1.5.1 - true. I'm aware of the enhancements (not scanning maps with no pointer types, doing stuff concurrently + reduced max gc time) but it is still an issue. We have some large lookup maps in memory (sometimes several GBs) which keep the GC busy even if it is just in the background - still burns CPU cycles + with the sysmon triggered forced GC (https://github.com/golang/go/issues/11637) we still pauses see annoying pauses. As we have several 100k requests per second even these small things matter ;-).   

Ciao,
Martin

**Comment by glycerine** [comment]
Sounds like a legitimate need and use case.

I took a quick stab at it. See the lastest push to master. I'm not at all convinced that the ZeroCell is recovered correctly. I'd appreciate it if you would test that.

**Comment by dynamix** [comment]
Awesome, will give it a shot tomorrow ;-)

**Comment by glycerine** [comment]
Just curious if this worked for your use case. No big deal if you haven't tried it yet.

**Comment by dynamix** [comment]
Uhm .. the thing is, I went a bit crazy because our requirements are different. I wanted to avoid:

- using interface{} type switching
- []byte Key/Value types
- a zero cell not in the mmap
- the approach you choose to create the StringHashTable or the ByteKeyHashTable


So I made a template out of offheap.go which can be used with genny. It is far from perfect, I haven't updated the docs yet and I should rename it because it diverged a bit from the original - I guess most people don't want to generate stuff. You can have a look here https://github.com/remerge/offheap

However the metadata saving in your repo seems to work!

**Comment by glycerine** [comment]
LOL. Awesome!

Hash tables are such intimate and performance sensitive things, that I fully expected any real use case to require heavy customization.  And you've proved that out! :-)

I don't think most people will mind the code generation, actually. If you get your repo to the point where you feel it is re-usable, let me know and I'll put a pointer in my docs to your version once it is ready.

Thanks for checking out the metadata saving. I'll close out this ticket.

Good luck with your project!
